# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022-2023 Dell Inc, or its subsidiaries.
---
version: '3.7'

services:

  bootstrap:
    build:
      context: .
    environment:
      SZTPD_INIT_PORT: 8080
      SZTPD_INIT_MODE: 1
      SZTPD_ACCEPT_CONTRACT: "Yes"
      SZTPD_INIT_ADDR: 0.0.0.0
    networks:
      - opi
    healthcheck:
      test: ["CMD-SHELL", "curl --fail -H Accept:application/yang-data+json http://127.0.0.1:$$SZTPD_INIT_PORT/.well-known/host-meta || exit 1"]
      interval: 6s
      retries: 5
      start_period: 20s
      timeout: 10s

  opi-test:
    image: docker.io/curlimages/curl:8.1.1
    depends_on:
      bootstrap:
        condition: service_healthy
    networks:
      - opi
    command: ["--fail", "-i", "--user", "my-admin@example.com:my-secret", "-H", "Accept:application/yang-data+json", "http://bootstrap:8080/restconf/ds/ietf-datastores:running"]

networks:
  opi:
