name: Release Please

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

permissions:
  contents: write
  pull-requests: write

jobs:
  call:
    uses: opiproject/opi-smbios-bridge/.github/workflows/release-please.yml@main
    secrets: inherit
